Repository thoth-station/thamos, pull requests merged in 2018-10, with the labels that each got.

#19 Use yaml.safe_load due to security reasons
  thamos/config.py
Labels: approved, size/XS

#23 Introduce --no-wait flag for not waiting for analysis to finish
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/M

#25 Regenerate client to include dependency monkey API
  Documentation/AnalysisListingResponse.md
  Documentation/AnalysisListingResponseInner.md
  Documentation/AnalysisStatusResponse.md
  Documentation/AnalysisStatusResponseStatus.md
  Documentation/AnalysisUnfinishedResultResponseStatus.md
  Documentation/DependencyMonkeyApi.md
  swagger-codegen.sh
  thamos/swagger_client/__init__.py
  thamos/swagger_client/thoth/__init__.py
  thamos/swagger_client/thoth/dependency_monkey_api.py
Labels: approved, size/XL

#24 Logs can be nullable
  swagger-codegen.sh
  thamos/swagger_client/models/analysis_log_response.py
Labels: approved, size/XS

#27 We use JSON as an output format
  Pipfile
  Pipfile.lock
  requirements.txt
  thamos/cli.py
Labels: approved, size/M

#29 Automatic update of dependency thoth-analyzer from 0.0.7 to 0.1.0
  Pipfile.lock
Labels: bot

#30 Automatic update of dependency urllib3 from 1.23 to 1.24
  Pipfile.lock
Labels: bot

#33 Automatic update of dependency python-dateutil from 2.7.3 to 2.7.4
  Pipfile.lock
Labels: bot

#31 Zuul pipelines use Thoth jobs
  .gitignore
  .zuul.yaml
Labels: size/XL, size/XS

#34 Automatic update of dependency python-dateutil from 2.7.4 to 2.7.5
  Pipfile.lock
Labels: bot
