Repository thoth-station/thamos, pull requests merged in 2018-09, with the labels that each got.

#6 added a job for creating releases
  .coafile
  .zuul.yaml
  Pipfile
  Pipfile.lock
  thamos/cli.py
  thamos/config.py
  thamos/data/defaultThoth.yaml
Labels: size/XL, size/XS

#10 Initial implementation of CLI
  Pipfile
  Pipfile.lock
  thamos/cli.py
  thamos/config.py
  thamos/data/defaultThoth.yaml
  thamos/discover.py
  thamos/exceptions.py
  thamos/lib.py
  thamos/swagger_client/models/python_stack.py
  thamos/utils.py
Labels: size/M, size/XL, size/XXL

#13 Make runtime environment a parameter to CLI
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/S

#16 Supress details from reports in table output
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/S

#18 Automatic update of dependency click from 6.7 to 7.0
  Pipfile.lock
Labels: bot

#20 Delete strict checks in nullable values
  swagger-codegen.sh
  thamos/lib.py
  thamos/swagger_client/__init__.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/analysis_listing_response.py
  thamos/swagger_client/models/analysis_listing_response_inner.py
  thamos/swagger_client/models/analysis_status_response.py
  thamos/swagger_client/models/analysis_status_response_status.py
  thamos/swagger_client/models/analysis_unfinished_result_response_status.py
Labels: size/L
