Repository thoth-station/thamos, pull requests merged in 2018-11, with the labels that each got.

#38 Automatic update of dependency urllib3 from 1.24 to 1.24.1
  Pipfile.lock
Labels: bot

#37 Automatic update of dependency texttable from 1.4.0 to 1.5.0
  Pipfile.lock
Labels: bot

#35 Do not use trailing slash in url
  thamos/lib.py
Labels: size/XS

#40 Update to reflect the current API implementation
  Documentation/AdminApi.md
  Documentation/AdviseApi.md
  Documentation/AnalysisResponse.md
  Documentation/DependencyMonkeyApi.md
  Documentation/EcosystemSolverApi.md
  Documentation/Environment.md
  Documentation/EnvironmentInner.md
  Documentation/ImageAnalysisApi.md
  Documentation/ImageMetadataResponse.md
  Documentation/Packages.md
  Documentation/PodInfo.md
  Documentation/ProvenanceApi.md
  Pipfile
  Pipfile.lock
  requirements.txt
  swagger-codegen.sh
  thamos/cli.py
  thamos/lib.py
  thamos/swagger_client/__init__.py
  thamos/swagger_client/api_client.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/analysis_response.py
  thamos/swagger_client/models/environment.py
  thamos/swagger_client/models/environment_inner.py
  thamos/swagger_client/models/image_metadata_response.py
  thamos/swagger_client/models/packages.py
  thamos/swagger_client/models/pod_info.py
  thamos/swagger_client/thoth/__init__.py
  thamos/swagger_client/thoth/admin_api.py
  thamos/swagger_client/thoth/advise_api.py
  thamos/swagger_client/thoth/buildlogs_api.py
  thamos/swagger_client/thoth/dependency_monkey_api.py
  thamos/swagger_client/thoth/ecosystem_solver_api.py
  thamos/swagger_client/thoth/environments_api.py
  thamos/swagger_client/thoth/image_analysis_api.py
  thamos/swagger_client/thoth/provenance_api.py
Labels: size/XXL

#44 Point to upshift test environment by default
  thamos/data/defaultThoth.yaml
Labels: approved, size/XS

#46 Fix report indexing
  thamos/cli.py
Labels: size/XS

#45 Propagate force parameters to bypass server-side cache
  thamos/cli.py
  thamos/lib.py
Labels: size/S

#42 Add long description for PyPI
  setup.py
Labels: human_intervention_required, size/XS

#47 Automatic update of dependency certifi from 2018.10.15 to 2018.11.29
  Pipfile.lock
Labels: bot
