Repository thoth-station/thamos, pull requests merged in 2018-12, with the labels that each got.

#48 Automatic update of dependency six from 1.11.0 to 1.12.0
  Pipfile.lock
Labels: bot

#49 Fixes and improvements in Thamos
  Documentation/InfoApi.md
  Documentation/PythonPackageIndexes.md
  Documentation/PythonPackageIndexesInner.md
  thamos/cli.py
  thamos/lib.py
  thamos/swagger_client/__init__.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/python_package_indexes.py
  thamos/swagger_client/models/python_package_indexes_inner.py
  thamos/swagger_client/thoth/__init__.py
  thamos/swagger_client/thoth/info_api.py
Labels: size/L

#54 Perform API discovery when communicating with remote
  Pipfile
  Pipfile.lock
  requirements.txt
  thamos/data/defaultThoth.yaml
  thamos/exceptions.py
  thamos/lib.py
Labels: size/L

#53 Remove unused parameters to CLI commands
  thamos/cli.py
Labels: size/S

#55 Remove no longer relevant TODO
  thamos/cli.py
Labels: size/XS

#56 Provide some defaults for runtime environmnet configuration
  thamos/data/defaultThoth.yaml
Labels: size/XS

#58 Use contoml instead of toml, it has prettier output
  Pipfile
  Pipfile.lock
  requirements.txt
  thamos/cli.py
Labels: size/M

#57 Warn on using insecure network without TLS
  thamos/config.py
  thamos/lib.py
Labels: size/M

#60 Release of version 0.1.0
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/M
