Repository thoth-station/thamos, pull requests merged in 2019-01, with the labels that each got.

#61 Fix exception happening if there was an error in analysis
  thamos/cli.py
Labels: size/XS

#62 Add missing requirements
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: size/M

#63 Automatic update of dependency texttable from 1.5.0 to 1.6.0
  Pipfile.lock
Labels: bot
