Repository thoth-station/thamos, pull requests merged in 2019-02, with the labels that each got.

#65 Provide routine for submitting and retrieving image analyses
  thamos/cli.py
  thamos/config.py
  thamos/lib.py
Labels: size/M

#64 Automatic update of dependency yaspin from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot

#66 Update README with lib/CLI instructions
  README.rst
Labels: size/M

#67 Update year in sources
  thamos/__init__.py
  thamos/cli.py
  thamos/config.py
  thamos/discover.py
  thamos/exceptions.py
  thamos/lib.py
  thamos/utils.py
Labels: size/S

#68 Introduce a way how to suppress TLS warnings
  README.rst
  thamos/config.py
Labels: size/S

#73 Introduce log and status sub-commands
  thamos/cli.py
  thamos/exceptions.py
  thamos/lib.py
Labels: size/M

#74 Fix clash of options for CLI
  thamos/cli.py
Labels: size/XS

#75 Explicitly propagate recommendation type if user asked so
  thamos/lib.py
Labels: size/XS

#71 Automatic update of dependency python-dateutil from 2.7.5 to 2.8.0
  Pipfile.lock
Labels: bot

#69 Automatic update of dependency distro from 1.3.0 to 1.4.0
  Pipfile.lock
Labels: bot

#76 Use black for formatting
  thamos/__init__.py
  thamos/cli.py
  thamos/config.py
  thamos/discover.py
  thamos/lib.py
  thamos/utils.py
Labels: size/L, size/XXL

#77 Perform autodiscovery for host runtime environment
  thamos/cli.py
  thamos/config.py
  thamos/data/defaultThoth.yaml
  thamos/discover.py
Labels: approved, size/M

#81 Automatic update of dependency thoth-analyzer from 0.1.0 to 0.1.2
  Pipfile.lock
Labels: bot

#82 Introduce output formats for Thamos
  thamos/cli.py
  thamos/lib.py
Labels: size/S

#83 Remove redundant parentheses
  thamos/lib.py
Labels: size/XS

#87 [WIP] a basic lockdown example
  examples/lockdown/.thoth.yaml
  examples/lockdown/Pipfile
Labels: approved, size/M

#89 Fix Coala issues
  thamos/discover.py
  thamos/lib.py
Labels: size/XS

#85 Automatic update of dependency texttable from 1.6.0 to 1.6.1
  Pipfile.lock
Labels: bot

#90 Release of version 0.2.0
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/M

#92 Release of version 0.3.0
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS
