Repository thoth-station/thamos, pull requests merged in 2019-03, with the labels that each got.

#94 Adjust recommendation type to latest
  examples/lockdown/.thoth.yaml
Labels: size/XS

#96 fixed the wrong version specifier
  examples/runtime-environment/Pipfile
Labels: approved, size/XS

#97 Add example flask application to verify stack works
  examples/lockdown/hello.py
Labels: size/S

#99 Remove requires section in example
  examples/runtime-environment/Pipfile
Labels: size/XS

#100 Add README for runtime environment scenario
  examples/runtime-environment/README.rst
  examples/runtime-environment/hello.py
  examples/scoring/.thoth.yaml
  examples/scoring/Pipfile
  examples/scoring/Pipfile.lock
  examples/scoring/README.rst
  examples/scoring/hello.py
  examples/scoring/resolved.json
Labels: approved, size/M, size/XXL

#101 Add files supporting "scoring" scenario
  examples/runtime-environment/hello.py
Labels: size/XS

#102 Add files supporting "scoring" scenario
  examples/scoring/.thoth.yaml
  examples/scoring/hello.py
Labels: size/S, size/XXL

#104 Move resolved stacks to misc repo
  examples/scoring/resolved.json
Labels: size/XXL

#103 Fix issues reported by coala
  examples/scoring/hello.py
Labels: approved, size/XS

#105 Demo with lower flask version
  examples/scoring/Pipfile.lock
Labels: size/XS

#106 Add ability to expand entries in configuration file
  README.rst
  thamos/cli.py
  thamos/config.py
Labels: size/M

#108 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/M

#109 Use safe_dump() instead of dump()
  thamos/cli.py
Labels: size/XS

#110 Regenerate swagger-client, add limit latest versions option
  Documentation/AdviseApi.md
  Documentation/ImageAnalysisApi.md
  Documentation/Info.md
  Documentation/InfoApi.md
  Documentation/ProvenanceApi.md
  thamos/cli.py
  thamos/lib.py
  thamos/swagger_client/__init__.py
  thamos/swagger_client/api_client.py
  thamos/swagger_client/configuration.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/info.py
  thamos/swagger_client/thoth/advise_api.py
  thamos/swagger_client/thoth/image_analysis_api.py
  thamos/swagger_client/thoth/info_api.py
  thamos/swagger_client/thoth/provenance_api.py
Labels: size/XL

#113 Adjust Thoth's configuration based on recommendations
  thamos/cli.py
  thamos/lib.py
Labels: size/M

#114 Automatic update of dependency pyyaml from 3.13 to 5.1
  Pipfile.lock
Labels: bot

#115 Regenerate client
  Documentation/ImageAnalysisApi.md
  thamos/lib.py
  thamos/swagger_client/__init__.py
  thamos/swagger_client/api_client.py
  thamos/swagger_client/configuration.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/advise_input.py
  thamos/swagger_client/models/advise_input_application_stack.py
  thamos/swagger_client/models/advise_input_runtime_environment.py
  thamos/swagger_client/models/analysis_listing_response.py
  thamos/swagger_client/models/analysis_log_response.py
  thamos/swagger_client/models/analysis_response.py
  thamos/swagger_client/models/analysis_response_error.py
  thamos/swagger_client/models/analysis_result_response.py
  thamos/swagger_client/models/analysis_result_response_metadata.py
  thamos/swagger_client/models/analysis_result_response_metadata_distribution.py
  thamos/swagger_client/models/analysis_result_response_metadata_distribution_version_parts.py
  thamos/swagger_client/models/analysis_result_response_metadata_python.py
  thamos/swagger_client/models/analysis_status_response.py
  thamos/swagger_client/models/analysis_status_response_status.py
  thamos/swagger_client/models/analysis_unfinished_result_response.py
  thamos/swagger_client/models/analysis_unfinished_result_response_status.py
  thamos/swagger_client/models/image_metadata_response.py
  thamos/swagger_client/models/info.py
  thamos/swagger_client/models/log.py
  thamos/swagger_client/models/log_metadata.py
  thamos/swagger_client/models/log_metadata_annotations.py
  thamos/swagger_client/models/python_package_indexes.py
  thamos/swagger_client/models/python_package_indexes_inner.py
  thamos/swagger_client/models/python_stack.py
  thamos/swagger_client/models/runtime_environment.py
  thamos/swagger_client/rest.py
  thamos/swagger_client/thoth/advise_api.py
  thamos/swagger_client/thoth/buildlogs_api.py
  thamos/swagger_client/thoth/environments_api.py
  thamos/swagger_client/thoth/image_analysis_api.py
  thamos/swagger_client/thoth/info_api.py
  thamos/swagger_client/thoth/provenance_api.py
Labels: size/M

#120 Release of version 0.3.1
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/M

#121 Adjust runtime-environment example to reflect data in Test environment
  examples/runtime-environment/.thoth.yaml
  examples/runtime-environment/Pipfile
  examples/runtime-environment/Pipfile.lock
  examples/runtime-environment/README.rst
Labels: size/L

#122 Fix Coala complains
  .thoth.yaml
Labels: size/XS

#123 Enable limit_latest_versions to be configured from configuration
  .thoth.yaml
  examples/lockdown/.thoth.yaml
  examples/runtime-environment/.thoth.yaml
  examples/scoring/.thoth.yaml
  thamos/cli.py
  thamos/data/defaultThoth.yaml
  thamos/lib.py
Labels: approved, size/S

#124 Match operating system with solver results
  examples/runtime-environment/.thoth.yaml
  thamos/data/defaultThoth.yaml
Labels: size/XS

#125 Used urljoin for maintaining semantic version of url
  thamos/config.py
Labels: approved, size/XS

#128 Bug fix on TLS turned on
  thamos/config.py
Labels: approved, size/XS
