Repository thoth-station/thamos, pull requests merged in 2019-04, with the labels that each got.

#129 Log Thoth's API URL to show to which instance a user talks to
  thamos/lib.py
Labels: approved, size/S

#131 added a container build script and adjusted some readmes
  README.rst
  build-container-image.sh
  examples/lockdown/README.rst
Labels: approved, size/M

#132 using -stage now, removed some quirks
  examples/lockdown/.thoth.yaml
  examples/runtime-environment/.thoth.yaml
  examples/scoring/.thoth.yaml
Labels: approved, size/S

#134 Automatic update of dependency urllib3 from 1.24.1 to 1.24.2
  Pipfile.lock
Labels: bot

#135 Re-generate for transition to Dgraph
  Documentation/Info.md
  thamos/swagger_client/models/info.py
Labels: approved, size/M

#136 Automatic update of dependency yaspin from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot
