Repository thoth-station/thamos, pull requests merged in 2019-07, with the labels that each got.

#183 Automatic update of dependency texttable from 1.6.1 to 1.6.2
  Pipfile.lock
Labels: bot

#185 Added origin option to provenance and advise
  thamos/lib.py
Labels: approved, size/S

#184 Fix issue #182
  thamos/lib.py
Labels: approved, size/S

#186 Add `nowrite` parameter to create_default_config
  thamos/config.py
Labels: approved, size/S

#188 Release of version 0.5.4
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/S

#190 Code error
  thamos/lib.py
Labels: approved, size/S

#192 Fix propagation of `limit_latest_versions` parameter
  thamos/lib.py
Labels: approved, size/S

#194 Fix issues with generated swagger client
  Documentation/AnalysisResultResponseMetadata.md
  Documentation/AnalysisResultResponseMetadataPython.md
  thamos/swagger_client/__init__.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/analysis_result_response_metadata.py
  thamos/swagger_client/models/analysis_result_response_metadata_python.py
Labels: approved, size/L

#198 Release of version 0.5.5
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/S

#200 Automatic update of dependency invectio from 0.0.3 to 0.0.4
  Pipfile.lock
Labels: bot

#191 supporting method for submitting whole build(imagestream and buildlog)
  thamos/lib.py
Labels: approved, size/L, size/M

#203 updated thamos with latest user-api
  Documentation/AdviseInputApplicationStack.md
  Documentation/Build.md
  Documentation/BuildAnalysisApi.md
  Documentation/BuildAnalysisResponse.md
  Documentation/BuildAnalysisResponseBaseImageAnalysis.md
  Documentation/BuildAnalysisResponseError.md
  Documentation/BuildAnalysisResponseErrorBaseImageAnalysis.md
  Documentation/BuildBuildLog.md
  Documentation/BuildlogsApi.md
  Documentation/PythonStack.md
  thamos/swagger_client/__init__.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/advise_input_application_stack.py
  thamos/swagger_client/models/build.py
  thamos/swagger_client/models/build_analysis_response.py
  thamos/swagger_client/models/build_analysis_response_base_image_analysis.py
  thamos/swagger_client/models/build_analysis_response_error.py
  thamos/swagger_client/models/build_analysis_response_error_base_image_analysis.py
  thamos/swagger_client/models/build_build_log.py
  thamos/swagger_client/models/python_stack.py
  thamos/swagger_client/thoth/__init__.py
  thamos/swagger_client/thoth/build_analysis_api.py
  thamos/swagger_client/thoth/buildlogs_api.py
Labels: approved, size/XXL

#204 Release of version 0.6.0
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#207 Automatic update of dependency invectio from 0.0.4 to 0.0.5
  Pipfile.lock
Labels: bot

#206 Fix issue if no report is generated by the recommendation engine
  thamos/cli.py
Labels: approved, size/XS

#209 Be more descriptive with logged message about library usage
  thamos/lib.py
Labels: approved, size/XS

#205 Correctly propagate invectio version to user-api after library usage detection
  thamos/lib.py
Labels: size/S

#210 Add ability to configure thamos using envvars
  thamos/cli.py
Labels: approved, size/S

#211 Propagate library usage for all Python libraries
  thamos/lib.py
Labels: size/XS

#212 Hot fix for accessing wrong variable
  thamos/lib.py
Labels: size/XS

#213 Expand configuration with environment variables
  thamos/config.py
Labels: size/XS

#215 Decrease maximum sleep time to be more responsive
  thamos/lib.py
Labels: approved, size/XS

#217 The configuration template can be user supplied
  thamos/cli.py
  thamos/config.py
Labels: approved, size/XS

#214 WIP: Propagate environment configuration in advise_here
  thamos/lib.py
Labels: approved, size/XS

#220 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/L
