Repository thoth-station/thamos, pull requests merged in 2019-09, with the labels that each got.

#245 Automatic update of dependency certifi from 2019.6.16 to 2019.9.11
  Pipfile.lock
Labels: bot

#246 Automatic update of dependency urllib3 from 1.25.3 to 1.25.4
  Pipfile.lock
Labels: bot

#247 Automatic update of dependency urllib3 from 1.25.4 to 1.25.5
  Pipfile.lock
Labels: bot

#248 Automatic update of dependency thoth-analyzer from 0.1.2 to 0.1.3
  Pipfile.lock
Labels: bot

#249 Automatic update of dependency pytest from 5.1.2 to 5.1.3
  Pipfile.lock
Labels: bot

#252 Automatic update of dependency urllib3 from 1.25.5 to 1.25.6
  Pipfile.lock
Labels: bot

#251 Do not send empty library usage
  thamos/lib.py
Labels: approved, size/XS

#253 Automatic update of dependency thoth-analyzer from 0.1.3 to 0.1.4
  Pipfile.lock
Labels: bot

#256 Automatic update of dependency pytest from 5.1.3 to 5.2.0
  Pipfile.lock
Labels: bot

#255 Print out Thoth backend version on `thamos version'
  thamos/cli.py
  thamos/config.py
Labels: approved, size/M, size/S
