Repository thoth-station/thamos, pull requests merged in 2019-12, with the labels that each got.

#290 Automatic update of dependency pyyaml from 5.1.2 to 5.2
  Pipfile.lock
Labels: bot, size/M

#293 Release of version 0.7.5
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/L

#291 there was some ( too much
  thamos/cli.py
Labels: size/XS

#295 Release of version 0.7.6
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#296 Automatic update of dependency thoth-analyzer from 0.1.5 to 0.1.6
  Pipfile.lock
Labels: bot, size/S

#297 Propagate is_s2i flag based to User API
  thamos/lib.py
Labels: approved, size/XS

#299 Automatic update of dependency thoth-analyzer from 0.1.6 to 0.1.7
  Pipfile.lock
Labels: bot, size/S

#300 Inform about no justification made
  thamos/cli.py
Labels: approved

#302 Release of version 0.7.7
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/S

#303 Automatic update of dependency pytest from 5.3.1 to 5.3.2
  Pipfile.lock
Labels: bot, size/M

#304 Automatic update of dependency daiquiri from 1.6.0 to 1.6.1
  Pipfile.lock
Labels: bot, size/M
