Repository thoth-station/thamos, pull requests merged in 2019-06, with the labels that each got.

#156 Adjust default Thoth host to talk to
  thamos/data/defaultThoth.yaml
Labels: approved, size/XS

#155 Provide ability to supply configuration file template
  README.rst
  thamos/cli.py
  thamos/config.py
Labels: approved, size/M

#157 State configuration option for disabling progressbar
  README.rst
Labels: approved, size/XS

#159 Thamos Library advise_here
  thamos/lib.py
Labels: size/M

#158 Use own user-agent for user requests
  thamos/lib.py
Labels: approved, size/XS

#160 Provenance here
  thamos/lib.py
Labels: approved, size/M, size/S

#162 Automatic update of dependency urllib3 from 1.24.3 to 1.25.3
  Pipfile.lock
Labels: bot

#163 Automatic update of dependency yaspin from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot

#164 Automatic update of dependency pyyaml from 5.1 to 5.1.1
  Pipfile.lock
Labels: bot

#165 Automatic update of dependency requests from 2.21.0 to 2.22.0
  Pipfile.lock
Labels: bot

#166 Automatic update of dependency invectio from 0.0.1 to 0.0.3
  Pipfile.lock
Labels: bot

#161 Include Thoth's configuration file for sdist distribution
  MANIFEST.in
Labels: approved, size/XS

#168 Release of version 0.4.3
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/M

#169 Automatic update of dependency certifi from 2019.3.9 to 2019.6.16
  Pipfile.lock
Labels: bot

#170 Fix handling based on arguments if no config file is needed
  thamos/lib.py
Labels: approved, size/S

#172 Release of version 0.5.0
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#174 Release of version 0.5.1
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#176 Release of version 0.5.2
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#178 Release of version 0.5.3
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#179 Fix URL to OpenAPI YAML
  swagger-codegen.sh
Labels: approved, size/XS

#180 Get analysis results
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/S

#181 Update docs on how autogenerating code is done
  README.rst
Labels: approved, size/S
