Repository thoth-station/thamos, pull requests merged in 2019-05, with the labels that each got.

#137 Automatic update of dependency urllib3 from 1.24.2 to 1.24.3
  Pipfile.lock
Labels: bot

#138 Integrate static analysis using Invectio
  Documentation/AdviseInput.md
  Pipfile
  Pipfile.lock
  thamos/cli.py
  thamos/lib.py
  thamos/swagger_client/models/advise_input.py
Labels: approved, size/M

#142 Release of version 0.4.0
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/M

#143 Use arguments instead of kwargs to be compatible with openapi
  thamos/lib.py
Labels: size/XS

#145 Release of version 0.4.1
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#146 Add missing Invectio requirement
  requirements.txt
Labels: size/XS

#148 Release of version 0.4.2
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#152 Report warning if no library usage was gathered
  thamos/lib.py
Labels: size/XS
