Repository thoth-station/thamos, pull requests merged in 2019-11, with the labels that each got.

#268 Automatic update of dependency python-dateutil from 2.8.0 to 2.8.1
  Pipfile.lock
Labels: bot

#273 Automatic update of dependency six from 1.12.0 to 1.13.0
  Pipfile.lock
Labels: bot

#275 save check for the stack-info
  thamos/cli.py
Labels: approved, size/M

#279 Automatic update of dependency urllib3 from 1.25.6 to 1.25.7
  Pipfile.lock
Labels: bot

#280 Release of version 0.7.3
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/S

#283 Release of version 0.7.4
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#284 Automatic update of dependency pytest from 5.2.2 to 5.2.3
  Pipfile.lock
Labels: bot, size/S

#285 Automatic update of dependency pytest from 5.2.3 to 5.2.4
  Pipfile.lock
Labels: bot, size/XS

#286 Automatic update of dependency pytest from 5.2.4 to 5.3.0
  Pipfile.lock
Labels: bot, size/S

#287 Automatic update of dependency pytest from 5.3.0 to 5.3.1
  Pipfile.lock
Labels: bot, size/M

#288 Automatic update of dependency certifi from 2019.9.11 to 2019.11.28
  Pipfile.lock
Labels: bot

#289 Automatic update of dependency thoth-analyzer from 0.1.4 to 0.1.5
  Pipfile.lock
Labels: bot, size/L
