Repository thoth-station/thamos, pull requests merged in 2019-08, with the labels that each got.

#216 WIP: Provide a way to note last analysis id into a temporary file
  README.rst
  thamos/cli.py
  thamos/lib.py
Labels: approved, do-not-merge/work-in-progress, size/M, work-in-progress

#221 Document environment variables which can be used during s2i
  README.rst
Labels: size/S, size/XS

#218 Filter out calls to Python's standard library
  thamos/lib.py
Labels: approved, size/XS

#222 Automatic update of dependency invectio from 0.0.5 to 0.0.6
  Pipfile.lock
Labels: bot

#223 Automatic update of dependency daiquiri from 1.5.0 to 1.6.0
  Pipfile.lock
Labels: bot

#224 Automatic update of dependency invectio from 0.0.6 to 0.0.7
  Pipfile.lock
Labels: bot

#225 Automatic update of dependency yaspin from 0.14.3 to 0.15.0
  Pipfile.lock
Labels: bot

#228 Release of version 0.7.0
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/S

#229 Always create config from template if template is set explictly
  thamos/cli.py
Labels: approved, size/S

#230 We require Python 3.6+
  README.rst
Labels: approved, size/XS

#231 Adjust the exception message when file is not set
  thamos/utils.py
Labels: approved, size/XS

#235 now using Fedora 30 and Python 3.7
  build-container-image.sh
Labels: approved, size/XS

#233 Switch from contoml to toml
  .coafile
  Pipfile
  Pipfile.lock
  setup.py
  tests/base.py
  tests/test_response.py
  thamos/cli.py
Labels: approved, size/L, size/XL

#234 Enable zuul-pytest on this repo
  .zuul.yaml
  tests/data/response_1.json
Labels: approved, size/XS, size/XXL

#237 Release of version 0.7.1
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/S

#238 Add missing toml in requirements.txt
  requirements.txt
Labels: size/XS

#241 Release of version 0.7.2
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#244 Automatic update of dependency pytest from 5.1.1 to 5.1.2
  Pipfile.lock
Labels: bot
