Repository thoth-station/thamos, pull requests merged in 2020-08, with the labels that each got.

#490 Automatic update of dependency yaspin from 0.18.0 to 1.0.0
  Pipfile.lock
Labels: approved, bot, size/M

#475 Swtich advise to result route
  swagger-codegen.sh
  thamos/lib.py
  thamos/swagger_client/api_client.py
  thamos/swagger_client/models/kebechet_webhook_input.py
  thamos/swagger_client/models/python_package_dependencies.py
  thamos/swagger_client/models/python_package_indexes.py
Labels: approved, size/M

#492 Release of version 0.11.0
  CHANGELOG.md
  thamos/__init__.py
Labels: approved, bot, size/S

#493 Fixed wrong exception
  thamos/exceptions.py
  thamos/lib.py
Labels: approved, size/XS

#494 Automatic update of dependency thoth-python from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: approved, bot, size/XS

#496 Release of version 0.11.1
  CHANGELOG.md
  thamos/__init__.py
Labels: approved, bot, size/XS

#497 Update default .thoth.yaml generated
  thamos/data/defaultThoth.yaml
Labels: approved, size/XS

#498 Automatic update of dependency thoth-common from 0.16.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/M

#499 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, size/M

#502 Add GitHub pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S

#504 Give up querying server if the response signalizes unsuccessful request
  thamos/lib.py
Labels: size/S

#505 Automatic update of dependency thoth-common from 0.16.1 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/S

#503 Do not retry client requests if the analysis was not successful
  thamos/lib.py
Labels: approved, size/XS
