Repository thoth-station/thamos, pull requests merged in 2020-11, with the labels that each got.

#568 Add logger name and padding to logs output
  thamos/lib.py
Labels: approved, size/S

#570 Fold on overflow when printing output
  thamos/cli.py
Labels: approved, size/XS

#572 Automatic update of dependency thoth-common from 0.20.2 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/M

#577 Release of version 1.2.0
  CHANGELOG.md
  thamos/__init__.py
Labels: approved, bot, size/S

#581 Implement thamos install command
  Pipfile
  Pipfile.lock
  requirements.txt
  thamos/cli.py
Labels: approved, size/L

#582 Switch recommended stack report and stack info
  thamos/cli.py
Labels: approved, size/S

#584 Automatic update of dependency certifi from 2020.6.20 to 2020.11.8
  Pipfile.lock
Labels: approved, bot, size/L

#585 Automatic update of dependency daiquiri from 2.1.1 to 3.0.0
  Pipfile.lock
Labels: approved, bot, size/L

#586 Automatic update of dependency invectio from 0.0.7 to 0.1.0
  Pipfile.lock
Labels: approved, bot, size/L

#588 Automatic update of dependency rich from 9.1.0 to 9.2.0
  Pipfile.lock
Labels: approved, bot, size/L

#591 Automatic update of dependency micropipenv from 1.0.0 to 1.0.1
  Pipfile.lock
Labels: approved, bot, size/L

#592 Release of version 1.3.0
  CHANGELOG.md
  thamos/__init__.py
Labels: approved, bot, size/S

#597 Adjust host to User API in the README
  README.rst
Labels: approved, size/XS

#569 Remove sleep before first attempt to obtain results
  thamos/lib.py
Labels: approved, size/XS

#599 Release of version 1.3.1
  CHANGELOG.md
  thamos/__init__.py
Labels: approved, bot, size/S

#601 Match colors shown in logs with logs in CLI
  thamos/lib.py
Labels: approved, size/XS

#600 Remove duplicite records in library usage
  thamos/lib.py
Labels: approved, size/XS

#602 Automatic update of dependency urllib3 from 1.25.11 to 1.26.2
  Pipfile.lock
Labels: approved, bot, size/L

#604 Automatic update of dependency requests from 2.24.0 to 2.25.0
  Pipfile.lock
Labels: approved, bot, size/L

#608 Set has no extend method but update
  thamos/lib.py
Labels: approved, size/XS

#605 Add option for writing advised manifest changes
  thamos/cli.py
Labels: approved, size/M

#610 Notify users about requirements used and project root
  thamos/cli.py
  thamos/utils.py
Labels: approved, size/S

#616 Notify users that development dependencies will not be installed
  thamos/cli.py
Labels: approved, size/S

#618 Notify users about hash mismatch in Pipenv files
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/M

#621 Refactor duplicate logic
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/S

#623 Introduce advise_using_config to enable supplying config file
  thamos/config.py
  thamos/lib.py
Labels: approved, size/L

#625 Adjust datatype of parameters in _write_files method
  thamos/cli.py
Labels: approved, size/XS

#632 Introduce thamos check command
  Pipfile
  Pipfile.lock
  thamos/cli.py
  thamos/config.py
Labels: approved, size/XL

#631 Introduce overlays to thamos
  README.rst
  thamos/cli.py
  thamos/config.py
  thamos/data/defaultThoth.yaml
  thamos/exceptions.py
  thamos/lib.py
Labels: approved, size/L

#638 Deliver missing package module to pypi github issue template
  .github/ISSUE_TEMPLATE/deliver_missing_module.md
Labels: size/S

#641 Add missing jsonschema to requirements.txt
  requirements.txt
Labels: approved, size/XS

#642 Improve obtaining Thoth backend version information
  thamos/cli.py
  thamos/config.py
Labels: approved, kind/feature, size/S

#649 Fix s2i detection
  thamos/lib.py
Labels: approved, size/XS
