Repository thoth-station/thamos, pull requests merged in 2020-10, with the labels that each got.

#542 Provide stack info when adviser fails
  thamos/cli.py
Labels: size/S

#551 Release of version 1.1.0
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#557 Automatic update of dependency thoth-common from 0.20.0 to 0.20.2
  Pipfile.lock
Labels: bot, size/L

#559 Automatic update of dependency pytest from 6.0.2 to 6.1.1
  Pipfile.lock
Labels: bot, size/L

#558 Automatic update of dependency rich from 7.0.0 to 9.1.0
  Pipfile.lock
Labels: bot, size/L

#556 Automatic update of dependency yaspin from 1.0.0 to 1.2.0
  Pipfile.lock
Labels: bot, size/L

#555 Automatic update of dependency urllib3 from 1.25.10 to 1.25.11
  Pipfile.lock
Labels: bot, size/L

#562 :star: pre-commit fixes
  .mypy.ini
  MANIFEST.in
Labels: approved, size/XS

#564 Release of version 1.1.1
  CHANGELOG.md
  thamos/__init__.py
Labels: approved, bot, size/S

#567 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/M
