Repository thoth-station/thamos, pull requests merged in 2020-06, with the labels that each got.

#430 Automatic update of dependency pytest from 5.4.2 to 5.4.3
  Pipfile.lock
Labels: bot, size/M

#431 Automatic update of dependency certifi from 2020.4.5.1 to 2020.4.5.2
  Pipfile.lock
Labels: bot, size/L

#432 Document runtime environments in the config file
  README.rst
  thamos/cli.py
Labels: approved, size/M

#434 Regenerated swagger to fix thamos error
  Documentation/AdviseApi.md
  thamos/swagger_client/rest.py
  thamos/swagger_client/thoth/advise_api.py
Labels: approved, size/S

#436 Release of version 0.10.3
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#442 Release of version 0.10.4
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/L

#443 Add thoth-common
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#445 Add thoth-common to requirements.txt
  requirements.txt
Labels: approved, size/XS

#448 Release of version 0.10.5
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/L

#450 Automatic update of dependency pytest-cov from 2.9.0 to 2.10.0
  Pipfile.lock
Labels: bot, size/M

#451 Automatic update of dependency pytest-timeout from 1.3.4 to 1.4.1
  Pipfile.lock
Labels: bot, size/XS

#452 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: bot, size/M

#453 Automatic update of dependency thoth-python from 0.9.2 to 0.10.0
  Pipfile.lock
Labels: bot, size/M

#454 Automatic update of dependency thoth-common from 0.13.11 to 0.13.12
  Pipfile.lock
Labels: approved, bot
