Repository thoth-station/thamos, pull requests merged in 2020-05, with the labels that each got.

#409 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/L

#408 Automatic update of dependency yaspin from 0.16.0 to 0.17.0
  Pipfile.lock
Labels: bot, size/XS

#412 Automatic update of dependency toml from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/M

#415 lib and CLI should have same behaviour
  thamos/lib.py
Labels: approved, size/M

#417 Release of version 0.10.1
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/S

#419 Added env variable to readme
  README.rst
Labels: approved, size/XS

#420 Added default timeout to be 15mins
  thamos/lib.py
Labels: approved, size/XS

#424 Automatic update of dependency six from 1.14.0 to 1.15.0
  Pipfile.lock
Labels: bot, size/L

#423 Timeout with nosignal
  thamos/exceptions.py
  thamos/lib.py
Labels: approved, size/XS

#426 Automatic update of dependency pytest-cov from 2.8.1 to 2.9.0
  Pipfile.lock
Labels: bot, size/S

#421 Introduce source_type flag
  thamos/cli.py
  thamos/config.py
  thamos/lib.py
Labels: approved, size/S

#425 Timeout fix
  README.rst
  thamos/exceptions.py
  thamos/lib.py
Labels: approved, size/S

#428 Release of version 0.10.2
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/S

#429 Increase timeout
  thamos/lib.py
Labels: approved, size/XS
