Repository thoth-station/thamos, pull requests merged in 2020-01, with the labels that each got.

#306 Update examples
  examples/runtime-environment/.thoth.yaml
  examples/scoring/.thoth.yaml
Labels: approved, size/S

#305 Happy new year!
  docs/source/conf.py
  tests/base.py
  tests/test_response.py
  thamos/__init__.py
  thamos/cli.py
  thamos/config.py
  thamos/discover.py
  thamos/exceptions.py
  thamos/lib.py
  thamos/utils.py
Labels: approved, size/S

#307 Automatic update of dependency pyyaml from 5.2 to 5.3
  Pipfile.lock
Labels: bot, size/L

#308 Automatic update of dependency pytest-timeout from 1.3.3 to 1.3.4
  Pipfile.lock
Labels: bot, size/L

#309 Add pip/pip-compile support
  Pipfile
  Pipfile.lock
  README.rst
  requirements.txt
  tests/data/response_1.json
  tests/test_response.py
  thamos/cli.py
  thamos/config.py
  thamos/data/defaultThoth.yaml
  thamos/utils.py
Labels: approved, size/XXL

#310 Automatic update of dependency thoth-python from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot, size/M

#311 Automatic update of dependency yaspin from 0.15.0 to 0.16.0
  Pipfile.lock
Labels: bot, size/M

#312 Automatic update of dependency six from 1.13.0 to 1.14.0
  Pipfile.lock
Labels: bot, size/L

#313 Automatic update of dependency daiquiri from 1.6.1 to 2.0.0
  Pipfile.lock
Labels: bot, size/S

#314 Automatic update of dependency thoth-analyzer from 0.1.7 to 0.1.8
  Pipfile.lock
Labels: bot, size/XS

#315 Automatic update of dependency pytest from 5.3.2 to 5.3.3
  Pipfile.lock
Labels: bot, size/S

#316 Automatic update of dependency pytest from 5.3.3 to 5.3.4
  Pipfile.lock
Labels: bot, size/S

#318 Automatic update of dependency urllib3 from 1.25.7 to 1.25.8
  Pipfile.lock
Labels: bot, size/S

#321 Fix method name
  thamos/lib.py
Labels: approved, size/XS

#320 Add support for GitHub integration to Thamos lib
  thamos/lib.py
Labels: approved, size/S

#322 Regenerate client with updated GitHub parameter types
  Documentation/QebHwtThamosAdviseInput.md
  thamos/swagger_client/models/qeb_hwt_thamos_advise_input.py
Labels: approved, size/L

#324 Release of version 0.8.0
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/S

#326 Automatic update of dependency pytest from 5.3.4 to 5.3.5
  Pipfile.lock
Labels: bot, size/L
