Repository thoth-station/thamos, pull requests merged in 2020-02, with the labels that each got.

#327 Modify parameters for GitHub App
  thamos/lib.py
Labels: approved, size/S

#328 remove unusued parameter
  thamos/lib.py
Labels: approved, size/XS

#331 Release of version 0.8.1
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#333 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#339 Automatic update of dependency requests from 2.22.0 to 2.23.0
  Pipfile.lock
Labels: bot, size/L

#336 Improve error handling when user-api is not available
  thamos/config.py
  thamos/exceptions.py
Labels: size/S

#342 Try to detect git origin with request
  thamos/lib.py
Labels: approved, size/S

#343 Automatic update of dependency daiquiri from 2.0.0 to 2.1.0
  Pipfile.lock
Labels: bot, size/M
