Repository thoth-station/thamos, pull requests merged in 2020-07, with the labels that each got.

#456 Automatic update of dependency certifi from 2020.4.5.2 to 2020.6.20
  Pipfile.lock
Labels: approved, bot, size/M

#460 Automatic update of dependency thoth-common from 0.13.12 to 0.13.13
  Pipfile.lock
Labels: approved, bot, size/M

#465 Automatic update of dependency thoth-common from 0.13.13 to 0.14.0
  Pipfile.lock
Labels: approved, bot, size/S

#467 Automatic update of dependency thoth-common from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/M

#468 Default to pipenv
  thamos/config.py
Labels: approved, size/XS

#470 Do not use urljoin logic for host
  thamos/config.py
Labels: approved, size/XS

#471 Use urljoin not relative to base
  thamos/config.py
Labels: approved, size/XS

#473 Release of version 0.10.6
  CHANGELOG.md
  thamos/__init__.py
Labels: approved, bot, size/S

#476 Remove latest versions limitation
  README.rst
  thamos/cli.py
  thamos/data/defaultThoth.yaml
  thamos/lib.py
Labels: approved, size/M

#477 Extend recommendation type
  thamos/cli.py
  thamos/data/defaultThoth.yaml
  thamos/lib.py
Labels: approved, size/S

#478 Automatic update of dependency urllib3 from 1.25.9 to 1.25.10
  Pipfile.lock
Labels: approved, bot, size/L

#479 Automatic update of dependency yaspin from 0.17.0 to 0.18.0
  Pipfile.lock
Labels: approved, bot, size/L

#480 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/L

#482 Automatic update of dependency pytest-timeout from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: approved, bot, size/L

#486 Automatic update of dependency thoth-common from 0.14.2 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/M

#487 Automatic update of dependency pytest from 5.4.3 to 6.0.1
  Pipfile.lock
Labels: approved, bot, size/M

#485 Running_swagger_codegen
  Documentation/AdviseApi.md
  Documentation/AnalysisStatusResponseStatus.md
  Documentation/AnalysisUnfinishedResultResponse.md
  thamos/swagger_client/__init__.py
  thamos/swagger_client/api_client.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/analysis_status_response_status.py
  thamos/swagger_client/models/analysis_unfinished_result_response.py
  thamos/swagger_client/models/kebechet_webhook_input.py
  thamos/swagger_client/models/python_package_dependencies.py
  thamos/swagger_client/models/python_package_indexes.py
  thamos/swagger_client/thoth/advise_api.py
Labels: approved, size/S
