Repository thoth-station/thamos, pull requests merged in 2020-03, with the labels that each got.

#349 Initial dependency lock
  Pipfile.lock
Labels: bot

#351 Automatic update of dependency pyyaml from 3.13 to 5.3.1
  Pipfile.lock
Labels: bot

#354 Fix analysis error detection
  thamos/cli.py
Labels: size/S

#358 Automatic update of dependency pyyaml from 5.3.1 to 3.13
  Pipfile.lock
Labels: bot, size/M

#359 Release of version 0.8.2
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/S

#362 Parse JSON log produced in the cluster on `thamos log`
  thamos/lib.py
Labels: size/M

#364 Introduce thamos advise with --dev switch
  README.rst
  thamos/cli.py
  thamos/lib.py
Labels: approved

#366 Release of version 0.9.0
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/L

#369 Release of version 0.9.1
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#370 Automatic update of dependency distro from 1.4.0 to 1.5.0
  Pipfile.lock
Labels: bot, size/S
