Repository thoth-station/thamos, pull requests merged in 2020-04, with the labels that each got.

#371 Automatic update of dependency pyyaml from 3.13 to 5.3.1
  Pipfile.lock
Labels: bot, size/M

#372 Do not fail if obtaining origin fails
  thamos/lib.py
Labels: approved

#374 Release of version 0.9.2
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/L

#377 Add new line after each log line if structured logging is turned off
  thamos/lib.py
Labels: approved, size/XS

#378 Update scoring example
  examples/scoring/.gitignore
  examples/scoring/.thoth.yaml
  examples/scoring/Pipfile
  examples/scoring/Pipfile.lock
  examples/scoring/requirements.txt
Labels: approved, size/L

#381 Use RHEL 8
  .thoth.yaml
Labels: approved, size/XS

#341 Drop raw HTTP support
  thamos/config.py
Labels: approved, size/M

#379 No CentOS, use RHEL
  .thoth.yaml
Labels: approved, size/XS

#380 Update runtime environment example
  examples/runtime-environment/.gitignore
  examples/runtime-environment/.thoth.yaml
  examples/runtime-environment/Pipfile
  examples/runtime-environment/Pipfile.lock
Labels: approved, size/L

#382 Automatic update of dependency certifi from 2019.11.28 to 2020.4.5
  Pipfile.lock
Labels: bot, size/M

#383 Automatic update of dependency certifi from 2020.4.5 to 2020.4.5.1
  Pipfile.lock
Labels: bot, size/S

#376 Update lockdown scenario
  examples/lockdown/.gitignore
  examples/lockdown/.thoth.yaml
  examples/lockdown/Pipfile
  examples/lockdown/README.rst
  examples/lockdown/hello.py
Labels: size/S

#387 Do not report exception if no configuration was found in the directory
  thamos/cli.py
Labels: approved, size/S

#389 Automatic update of dependency urllib3 from 1.25.8 to 1.25.9
  Pipfile.lock
Labels: bot, size/L

#390 Added missing docstring
  thamos/cli.py
Labels: approved, size/XS

#391 Add check on requirements format if missing from config file
  thamos/config.py
  thamos/exceptions.py
  thamos/lib.py
Labels: approved, size/M

#393 Automatic update of dependency thoth-python from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot, size/S

#395 Release of version 0.9.3
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/S

#396 Provide platform in Thoth's configuration file
  README.rst
  thamos/config.py
  thamos/data/defaultThoth.yaml
  thamos/discover.py
Labels: approved, size/M

#397 Implement retry mechanism to avoid flakes
  thamos/lib.py
Labels: approved, size/M

#399 Automatic update of dependency click from 7.1.1 to 7.1.2
  Pipfile.lock
Labels: bot, size/S

#401 Release of version 0.9.4
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/XS

#405 Regenerate client to reflect recent API schema changes
  Documentation/InfoApi.md
  Documentation/KebechetApi.md
  Documentation/KebechetWebhookInput.md
  Documentation/PythonPackagesApi.md
  Documentation/RuntimeEnvironment.md
  thamos/swagger_client/__init__.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/kebechet_webhook_input.py
  thamos/swagger_client/models/runtime_environment.py
  thamos/swagger_client/thoth/info_api.py
  thamos/swagger_client/thoth/kebechet_api.py
  thamos/swagger_client/thoth/python_packages_api.py
Labels: approved, size/XL

#402 Fix inconsistency in wait time printed
  thamos/lib.py
Labels: approved

#400 Remove unused variable
  thamos/lib.py
Labels: approved, size/XS

#403 Document environment variables that can be used
  README.rst
Labels: approved, size/XS

#404 Configure requirements format using env variables passed to build
  README.rst
  thamos/config.py
  thamos/data/defaultThoth.yaml
Labels: approved, size/S

#407 Release of version 0.10.0
  CHANGELOG.md
  thamos/__init__.py
Labels: bot, size/S
