Repository thoth-station/thamos, pull requests merged in 2020-09, with the labels that each got.

#500 Perform status obtaining request only for debug level
  thamos/lib.py
Labels: approved, size/S

#501 Produce TLS related warning just once per session in logs
  thamos/config.py
Labels: approved, size/XS

#507 Release of version 0.12.0
  CHANGELOG.md
  thamos/__init__.py
Labels: approved, bot, size/S

#509 Automatic update of dependency thoth-common from 0.17.0 to 0.17.2
  Pipfile.lock
Labels: approved, bot, size/S

#511 Fix environment dict expansion
  thamos/config.py
Labels: approved, size/XS

#513 Release of version 0.12.1
  CHANGELOG.md
  thamos/__init__.py
Labels: approved, bot, size/XS

#515 Raise appropriate exception when Thoth backend is down
  thamos/config.py
Labels: approved, size/XS

#516 Fix URL when obtaining results for provenance and image analyses
  thamos/lib.py
Labels: size/XS

#519 Automatic update of dependency texttable from 1.6.2 to 1.6.3
  Pipfile.lock
Labels: approved, bot, size/M

#520 Release of version 0.12.2
  CHANGELOG.md
  thamos/__init__.py
Labels: approved, bot, size/S

#518 Use rich output to improve console output
  thamos/cli.py
  thamos/config.py
Labels: approved, size/M

#524 Fix missing requirements
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: size/L

#521 Click aliased group
  thamos/cli.py
Labels: approved, size/S

#529 Release of version 1.0.0
  CHANGELOG.md
  thamos/__init__.py
Labels: approved, bot, size/XS

#530 Automatic update of dependency thoth-common from 0.18.3 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/M

#525 Automatic update of dependency rich from 6.1.2 to 6.2.0
  Pipfile.lock
Labels: approved, bot, size/XS

#527 Link document with recommendation types
  README.rst
  thamos/data/defaultThoth.yaml
Labels: size/XS

#532 Allow users not to submit lock file with the request
  README.rst
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/S

#533 Automatic update of dependency rich from 6.2.0 to 7.0.0
  Pipfile.lock
Labels: approved, bot, size/M

#535 Automatic update of dependency thoth-python from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: approved, bot, size/M

#536 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/M

#538 Release of version 1.0.1
  CHANGELOG.md
  thamos/__init__.py
Labels: approved, bot, size/S
