Repository thoth-station/thamos, pull requests merged in 2021-06, with the labels that each got.

#860 Respect tls_verify configuration option from the config file
  thamos/cli.py
  thamos/config.py
  thamos/lib.py
Labels: approved, size/M

#865 Regenerate client to support labels
  Documentation/AdviseInput.md
  thamos/swagger_client/models/advise_input.py
Labels: approved, size/XS

#864 Introduce labels concept
  README.rst
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/M

#866 add project_url so that we show more info on pypi :pencil:
  setup.py
Labels: approved, size/XS

#872 Require at least one runtime environment set in the config file
  thamos/config.py
Labels: approved, size/XS

#873 Use latest recommendations by default
  thamos/data/defaultThoth.yaml
Labels: approved, size/XS

#875 Log recommendation type used in the advise request
  thamos/lib.py
Labels: approved, lgtm, size/XS

#876 Adjust copyright notice in headers
  build-container-image.sh
  tests/base.py
  tests/test_response.py
  thamos/__init__.py
  thamos/cli.py
  thamos/config.py
  thamos/discover.py
  thamos/exceptions.py
  thamos/lib.py
  thamos/utils.py
Labels: approved, size/S

#879 Add a link to labels demo
  README.rst
Labels: approved, size/XS

#878 advise_here uses overlay directories
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/L

#886 Set Python version based on .thoth.yaml file
  thamos/cli.py
Labels: approved, lgtm, size/XS
