Repository thoth-station/thamos, pull requests merged in 2021-03, with the labels that each got.

#776 Keep Thoth section in Pipfile if Pipenv files are generated using Thoth
  tests/test_response.py
  thamos/cli.py
Labels: approved, size/XS

#779 Fix aggregating library usage
  thamos/cli.py
  thamos/config.py
  thamos/lib.py
Labels: approved, size/S

#783 allow aicoe-ci to release the module to pypi
  .aicoe-ci.yaml
Labels: approved, size/XS

#790 Exclude autogenerated code from pre-commit
  .mypy.ini
  .pre-commit-config.yaml
Labels: approved, lgtm, ok-to-test, size/S

#795 Improve help messages printed to users
  thamos/cli.py
Labels: size/L

#787 Document thamos install in the README file
  README.rst
Labels: size/S

#794 thamos ci updates
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  .prow.yaml
Labels: size/M

#796 Issue an error if a user tries to install missing dev requirements
  thamos/exceptions.py
  thamos/lib.py
Labels: size/S

#801 Discover base image based on IMAGE_NAME and IMAGE_TAG
  thamos/discover.py
Labels: approved, lgtm, size/S

#803 State .venv in the README file
  README.rst
Labels: approved, size/XS

#805 Add py.typed
  setup.py
  thamos/py.typed
Labels: lgtm, size/XS

#808 Introduce a parameter to adjust timeout for analyses
  thamos/lib.py
Labels: approved, size/M

#811 Handle cases when virtual environment was not created yet
  thamos/cli.py
Labels: size/S

#812 Be more verbose when printing host information detected
  thamos/discover.py
Labels: size/XS

#821 Fix typo in the parameter
  thamos/lib.py
Labels: size/XS

#824 Fix accidentally added comma
  thamos/cli.py
Labels: size/XS

#827 Adjust TimeoutError message
  thamos/lib.py
Labels: approved, size/XS

#828 remove reviewer
  OWNERS
Labels: approved, size/XS

#820 Add URL Home page
  setup.py
Labels: approved, lgtm, size/XS
