Repository thoth-station/thamos, pull requests merged in 2021-07, with the labels that each got.

#894 new flake8 standard added ignoring
  .pre-commit-config.yaml
Labels: approved, size/XS

#893 Fix thamos provenance-check command
  thamos/config.py
  thamos/lib.py
Labels: approved, lgtm, size/XS

#892 Adjust ci
  .mypy.ini
  .pre-commit-config.yaml
  .prow.yaml
Labels: approved, size/M

#881 Provide a way to report relevant information on issues
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/M

#880 Fix spacing in CLI examples
  thamos/cli.py
Labels: approved, size/M

#900 Implement thamos graph command
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/L
