Repository thoth-station/thamos, pull requests merged in 2021-11, with the labels that each got.

#927 Use https in pre-commit repo links
  .pre-commit-config.yaml
Labels: approved, size/XS

#926 Update the labels of bug/rfe issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, size/XS

#933 Remove examples/ directory, use thoth-station/cli-examples repo
  examples/lockdown/.gitignore
  examples/lockdown/.thoth.yaml
  examples/lockdown/Pipfile
  examples/lockdown/README.rst
  examples/lockdown/hello.py
  examples/runtime-environment/.gitignore
  examples/runtime-environment/.thoth.yaml
  examples/runtime-environment/Pipfile
  examples/runtime-environment/Pipfile.lock
  examples/runtime-environment/README.rst
  examples/runtime-environment/hello.py
  examples/scoring/.gitignore
  examples/scoring/.thoth.yaml
  examples/scoring/README.rst
  examples/scoring/hello.py
  examples/scoring/requirements.txt
Labels: approved, size/XL, lgtm

#943 Drop hardware subcommand
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/M

#936 Fix support command that calls discover methods
  thamos/lib.py
Labels: approved, size/XS

#939 Fix support command if no last analysis id is found
  thamos/lib.py
Labels: approved, size/XS

#941 Swagger codegen dropped branch and created a tag instead
  swagger-codegen.sh
Labels: approved, size/S

#940 Aggregate also standard imports from user's code
  thamos/lib.py
Labels: approved, size/XS

#948 add kebechet to crossroads in docs
  docs/source/index.rst
Labels: approved, size/XS

#945 Feature/use new endpoint
  thamos/cli.py
  thamos/lib.py
Labels: size/L, approved

#954 Do not handle exceptions during API, let them propagate
  thamos/lib.py
Labels: approved, size/S

#956 Show an example with imports with a star
  thamos/cli.py
Labels: approved, size/S
