Repository thoth-station/thamos, pull requests merged in 2021-02, with the labels that each got.

#709 Regenerate client to support S2I endpoint
  Documentation/S2IPythonResponse.md
  Documentation/S2IPythonResponseS2i.md
  Documentation/S2iApi.md
  thamos/swagger_client/__init__.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/s2_i_python_response.py
  thamos/swagger_client/models/s2_i_python_response_s2i.py
  thamos/swagger_client/thoth/__init__.py
  thamos/swagger_client/thoth/s2i_api.py
Labels: approved, lgtm, size/M

#710 Fix quoting in CUDA version in the config file
  thamos/config.py
  thamos/data/defaultThoth.yaml
Labels: approved, lgtm, size/XS

#713 Update S2I endpoint response
  Documentation/PythonPlatforms.md
  thamos/swagger_client/models/python_platforms.py
Labels: size/XS

#714 WIP: Regenerate to support new User API structure
  Documentation/HardwareApi.md
  Documentation/ImageAnalysisApi.md
  Documentation/InfoApi.md
  Documentation/InlineResponse200.md
  Documentation/InlineResponse2001.md
  Documentation/InlineResponse2001Parameters.md
  Documentation/InlineResponse2002.md
  Documentation/InlineResponse2002SoftwareEnvironments.md
  Documentation/InlineResponse200HardwareEnvironments.md
  Documentation/InlineResponse200Parameters.md
  thamos/swagger_client/__init__.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/inline_response200.py
  thamos/swagger_client/models/inline_response2001.py
  thamos/swagger_client/models/inline_response2002.py
  thamos/swagger_client/models/inline_response2002_software_environments.py
  thamos/swagger_client/models/inline_response200_hardware_environments.py
  thamos/swagger_client/models/inline_response200_parameters.py
  thamos/swagger_client/models/inline_response200_runtime_environments.py
  thamos/swagger_client/thoth/__init__.py
  thamos/swagger_client/thoth/hardware_api.py
  thamos/swagger_client/thoth/image_analysis_api.py
  thamos/swagger_client/thoth/info_api.py
Labels: do-not-merge/work-in-progress, size/L

#717 Regenerate client with nullable hardware parameters
  Documentation/InlineResponse200HardwareEnvironments.md
  thamos/swagger_client/models/inline_response200_hardware_environments.py
Labels: size/S

#716 Provide thamos hw and thamos s2i commands
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/L

#718 Fix link to Thoth s2i description
  thamos/cli.py
Labels: size/XS

#719 Fix thoth s2i link
  README.rst
Labels: size/S

#722 Add support for passing options to pip during thamos install
  thamos/cli.py
  thamos/lib.py
Labels: approved, lgtm, size/S

#733 Fix URL creation when obtaining analysis status
  thamos/lib.py
Labels: approved, size/XS

#738 Regenerate client respecting API changes
  Documentation/PythonPackageDependencies.md
  Documentation/PythonPackageDependenciesDependencies.md
  Documentation/PythonPackageIndexes.md
  Documentation/PythonPackageIndexesIndexes.md
  Documentation/PythonPackageIndexesInner.md
  Documentation/PythonPackageMetadataResponse.md
  Documentation/PythonPackageMetadataResponseMetadata.md
  Documentation/PythonPackagesApi.md
  Documentation/PythonPackagesCountInfoResponse.md
  Documentation/PythonPlatforms.md
  thamos/swagger_client/__init__.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/python_package_dependencies.py
  thamos/swagger_client/models/python_package_dependencies_dependencies.py
  thamos/swagger_client/models/python_package_indexes.py
  thamos/swagger_client/models/python_package_indexes_indexes.py
  thamos/swagger_client/models/python_package_metadata_response.py
  thamos/swagger_client/models/python_package_metadata_response_metadata.py
  thamos/swagger_client/models/python_packages_count_info_response.py
  thamos/swagger_client/models/python_packages_count_info_response_error.py
  thamos/swagger_client/models/python_platforms.py
  thamos/swagger_client/thoth/python_packages_api.py
Labels: approved, lgtm, size/L

#740 Update thoth yaml
  .thoth.yaml
Labels: approved, size/XS

#743 Introduce thamos index command for listing package indexes available
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/M

#757 Turn on overlays by default
  thamos/data/defaultThoth.yaml
Labels: approved, size/XS

#758 Support requirement files when `thamos add` or `thamos remove` is called
  thamos/config.py
Labels: approved, lgtm, size/M

#755 Generate default Pipfile if none is present in the project
  thamos/config.py
Labels: approved, size/XS

#761 Create directory structure for overlay if not present yet
  thamos/config.py
Labels: approved, size/XS

#762 Handle CLI exceptions
  thamos/cli.py
Labels: size/S

#763 Any invalid thamos command notifies about creating overlays
  thamos/cli.py
  thamos/config.py
Labels: size/M

#765 Fix obtaining status information for provenance-checker
  thamos/lib.py
Labels: size/XS

#766 Keep Thoth section when generating Pipfile
  thamos/config.py
Labels: approved, size/XS

#767 Add warning message when repo setup might be misleading
  thamos/config.py
Labels: approved, lgtm, size/S

#768 Adjust client to respect recent API response schema changes
  swagger-codegen.sh
  thamos/lib.py
  thamos/swagger_client/models/python_package_indexes_indexes.py
Labels: approved, size/XS

#771 Reset loaded config in memory
  thamos/config.py
  thamos/lib.py
Labels: approved, size/S
