Repository thoth-station/thamos, pull requests merged in 2022-10, with the labels that each got.

#1182 Update defaultThoth.yaml
  thamos/data/defaultThoth.yaml
Labels: approved, size/XS, lgtm

#1186 Regenerate swagger client
  Documentation/AdviseApi.md
  Documentation/AdviseInput.md
  Documentation/CallbackInfo.md
  Documentation/PythonPackagesApi.md
  thamos/swagger_client/__init__.py
  thamos/swagger_client/models/__init__.py
  thamos/swagger_client/models/advise_input.py
  thamos/swagger_client/models/callback_info.py
  thamos/swagger_client/thoth/advise_api.py
  thamos/swagger_client/thoth/python_packages_api.py
Labels: approved, size/M, lgtm

#1189 filter option to results
  thamos/cli.py
Labels: approved, size/M

#1195 Check if the cuda_version is none
  thamos/config.py
Labels: approved, size/XS, lgtm
