Repository thoth-station/thamos, pull requests merged in 2022-02, with the labels that each got.

#1030 Add missing parameters when querying container images
  thamos/lib.py
Labels: approved, size/XS

#1031 Fix list_thoth_container_images parameter
  thamos/cli.py
Labels: approved, size/XS

#1033 Add myself to maintainers
  .thoth.yaml
Labels: approved, size/XS

#1036 Introduce pedantic runs
  README.rst
  thamos/cli.py
  thamos/discover.py
  thamos/exceptions.py
  thamos/lib.py
Labels: size/L, approved

#1042 Relax verbosity in messages logged in the discover module
  thamos/discover.py
Labels: approved, size/S

#1043 Add myself to reviewers
  OWNERS
Labels: approved, size/XS

#1047 Respect runtime environments in commands
  thamos/cli.py
Labels: approved, size/M

#1044 Report if configuration check passes
  thamos/cli.py
Labels: approved, size/XS

#1055 Print thamos check results only if any result reported
  thamos/cli.py
Labels: approved, size/S

#1058 Remove rm-build-container-image.sh
  build-container-image.sh
Labels: approved, size/M

#1061 Fix thamos venv not printing virtualenv path
  thamos/cli.py
Labels: approved, size/XS
