Repository thoth-station/thamos, pull requests merged in 2022-01, with the labels that each got.

#984 Fix type hint for list_thoth_container_images
  thamos/lib.py
Labels: approved, size/XS

#981 Respect nullable values in container-images response
  swagger-codegen.sh
  thamos/swagger_client/models/container_images_response_container_images.py
Labels: approved, size/S

#985 Update documentation stating environments and images
  README.rst
Labels: approved, size/S

#986 Add Maya to OWNERS
  OWNERS
Labels: approved, size/XS

#972 Parametrize obtaining images
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/M

#971 Introduce thamos verify command to check lockfile hash
  thamos/cli.py
Labels: approved, size/M

#989 Unify table reported when `thamos check' called
  thamos/cli.py
Labels: approved, size/M

#990 Unify table reported when `thamos indexes' called
  thamos/cli.py
Labels: approved, size/M

#991 Implement translation for table keys and thamos images report
  thamos/cli.py
Labels: approved, size/M

#992 Use dash instead of underscore in options
  thamos/cli.py
Labels: approved, size/XS

#973 Adjust reporting when `thamos discover' does not find any package
  thamos/lib.py
Labels: approved, size/M

#993 A minor fix in docstring
  thamos/lib.py
Labels: approved, size/XS

#995 Make sure the import reports are unified
  thamos/cli.py
Labels: approved, size/XS

#996 Choose spinners, wisely
  thamos/lib.py
Labels: approved, size/M

#999 Do not include std imports and builtins in thamos discover
  thamos/cli.py
  thamos/lib.py
Labels: approved, size/S

#974 Update GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, size/S

#1002 Fix message reported
  thamos/config.py
Labels: approved, size/XS

#1003 Check what type of document users ask when performing thamos graph
  thamos/lib.py
Labels: approved, size/S

#1015 Report import errors for whatprovides and discover too
  thamos/cli.py
  thamos/lib.py
Labels: size/L, approved

#1016 Enable TLS verification
  .thoth.yaml
Labels: approved, size/XS

#1018 Fix text in docstring of the parameter
  thamos/cli.py
Labels: approved, size/XS

#1017 Add metavar for source path
  thamos/cli.py
Labels: approved, size/XS

#1020 Provide short help to fit terminal width
  thamos/cli.py
Labels: approved, size/XS

#1021 Handle cases when CPU detection fails
  thamos/config.py
Labels: approved, size/XS

#1027 Update PR template for new module release
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/XS
