Repository thoth-station/thamos, pull requests merged in 2022-09, with the labels that each got.

#1167 Remove the remaining github issue/pr templates
  .github/ISSUE_TEMPLATE/kebechet_info.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/M

#1158 Avoid empty values in thoth images command
  thamos/cli.py
Labels: approved, size/XS, lgtm

#1134 Extend and unit test thamos discover
  .pre-commit-config.yaml
  MANIFEST.in
  tests/data/cpu_info_file
  tests/test_discover.py
  thamos/config.py
  thamos/discover.py
Labels: approved, size/XL

#1177 added diff command and flag
  thamos/cli.py
  thamos/cli_config.py
  thamos/lib.py
Labels: size/L, approved, lgtm
