Repository thoth-station/thamos, pull requests merged in 2022-08, with the labels that each got.

#1159 Ignore `.venv` content when getting static analysis of files
  thamos/lib.py
Labels: approved, size/XS, lgtm

#1155 Experimental --scoring flag for scorecards metrics
  thamos/cli.py
Labels: size/L, approved

#1162 Remove GitHub issue templates so that defaults are used
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/deliver_missing_module.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved
