Repository thoth-station/thamos, pull requests merged in 2022-03, with the labels that each got.

#1066 Increase thamos timeout to 45 minutes
  thamos/lib.py
Labels: approved, size/XS

#1076 Regenerate openapi schema to fix serialization issues
  Documentation/AdviserResultResponseResultReport.md
  Documentation/AdviserResultResponseResultReportProducts.md
  thamos/swagger_client/models/adviser_result_response_result_report.py
  thamos/swagger_client/models/adviser_result_response_result_report_products.py
Labels: approved, size/XS

#1084 Update GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
Labels: size/L, approved

#1086 Fix python version display in support command
  thamos/lib.py
Labels: approved, size/XS

#1083 Add link to container image analyses from Thoth Search UI in thamos images
  thamos/cli.py
  thamos/config.py
Labels: approved, size/S

#1090 Fix key error for `thamos graph` when no --dev flag was supplied
  thamos/lib.py
Labels: approved, size/S

#1096 Fix click version in pre-commit config
  .pre-commit-config.yaml
Labels: approved, size/XS
